### PR TITLE
Add wasi examples

### LINKED ISSUE #11: wasi example not mentioned in the README
Not sure if this was omitted on purpose. If not it'd be nice if the information is added.

### PR DESCRIPTION
**Pull request by fgsch**
Fixes #11.

### CODE REVIEW

**Comment by MarkMcCaskey** [comment]
Thanks this looks good!  Can you update the wasi file names to be links like the other example? I'll ship it when ready!

Note to myself: I thought I had updated the WASI instructions to use [wasienv](https://github.com/wasienv/wasienv) which is much simpler than that complicated command.  I'll make that change after this ships though!

**Comment by fgsch** [comment]
Which one? It is a link already.

**Comment by fgsch** [comment]
I think you are seeing a side effect of GH.

**Comment by MarkMcCaskey** [comment]
> Which one? It is a link already.

The wasi example ones that you added.  To clarify:

```
See [`wasmer-c-api-example.c`](./wasmer-c-api-example.c) and [`wasmer-wasi-c-api-example.c`](./wasmer-wasi-c-api-example.c) for the example implementations.
```

and

```
The `wasm-sample-app` directory contains an example C wasm app to run in the embedder app.
The `wasm-sample-app` and `wasmer-wasi-c-api-example` directories contain example C wasm apps to run in the embedder app.
```

are what I see.  The top one contains markdown links, like ```[`path`]``` and the new ones don't;

 > I think you are seeing a side effect of GH

If you mean that GitHub is parsing the markdown and creating links then I agree.  If you mean something else, then I think I don't understand.

**Comment by MarkMcCaskey** [comment]
Oops! You're completely right!  I've been misreading the file, I meant to ask for links to the sample app directories -- sorry about the confusion!

**Review by MarkMcCaskey — APPROVED** [review]
And actually, that change is kind of unrelated so we can make that change separately.

Thanks for the PR and the correction 😄

**Pull request merged**
